# This is a basic workflow to help you get started with Actions

name: paddleCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: test
        shell: pwsh
        run: |
          cd c:\
          mkdir c:\paddle
          cd paddle
          
      - uses: actions/checkout@v2
   
      - name: Disk Space info
        shell: pwsh
        run: |
          python diskspace.py
          
      - name: cmake build  
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          ls
          cmake --version
          python --version
          pip install numpy protobuf wheel
          dir
          cmake -B c:\paddle -G "Visual Studio 15 2017 Win64"  -DON_INFER=ON -DWITH_MKL=ON  -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3
          dir
          cmake --build c:\paddle --target inference_lib_dist
          ls

      - uses: actions/upload-artifact@v2
        with:
            name: build-artifact
            path: c:\paddle
          
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
